### Conditional Statement for Python Programming

<b>created by</b> : Muhammad Ammar Fauzan | maf.fauzan@gmail.com

#### Pengenalan Conditional Statement

In [ ]:
#Concept Dasar Conditional Statement

if expression1:
    statement1(s)
elif expression2:
    statement2(s)
elif expression3:
    statement3(s)
...
else:
    statement4(s)

In [29]:
#implementasi if pada python programming 1 kondisi
current_status = 'on-delivery'
barang_diterima = True

if barang_diterima==True: #expression 'jika' berwujud nilai boolean True
    current_status='Delivered' #jika true maka. . .

#notes seteleh if conditional gunakan ':' kemudian enter maka cursor akan menjorok indention
print(current_status)

Delivered

In [30]:
#implementasi if pada python programming 1 kondisi
current_status = 'on-delivery'
barang_diterima = True

if barang_diterima==True: #expression 'jika' berwujud nilai boolean True
    current_status='Delivered' #jika true maka. . .
else: #optional
    pass

print(current_status)

Delivered

In [31]:
#implementasi if else pada python programming 2 kondisi
total_visit = 34

if total_visit > 30: #expression melakukan pengecekan dengan value True / False, jika True akan masuk ke kondisi maka
    category = 'Potential Buyer' #jika True maka category akan bernilai Potential Buyer
else: #jika expression awal False maka akan masuk ke kondisi else
    category = 'Not Potential Buyer'

print(category)

Potential Buyer

In [32]:
#implementasi if else pada python programming 2 kondisi
total_visit = 100

if total_visit > 30: #expression melakukan pengecekan dengan value True / False, jika True akan masuk ke kondisi maka
    category = 'Potential Buyer' #jika True maka category akan bernilai Potential Buyer
else: #jika expression awal False maka akan masuk ke kondisi else
    category = 'Not Potential Buyer'

print(category)

Potential Buyer

In [33]:
rating = 5

if rating >= 4:
    result = 'Puas'
else:
    result = 'Tidak Puas'

print(result)

Puas

In [34]:
rating = 2

if rating >= 4:
    result = 'Puas'
else:
    result = 'Tidak Puas'

print(result) #result Tidak Puas dikarenakan tidak memenuhi kondisi if sehingga masuk kondisi else

Tidak Puas

#### One Liner Conditional Statement

In [35]:
#one liner conditional statement
rating = 2

result = 'Puas' if rating >= 4 else 'Tidak Puas'
print(result)

Tidak Puas

In [36]:
#one liner conditional statement
rating = 4

result = 'Puas' if rating >= 4 else 'Tidak Puas'
print(result)

Puas

In [37]:
#one liner conditional statement more than 1 conditional
num = 1

result = 'Positif' if num > 0 else 'Negatif' if num < 0 else 'Netral'
print(result)

Positif

In [ ]:
#one liner conditional statement more than 1 conditional
num = 4

result = 'Positif' if num > 0 else 'Netral' if num == 0 else 'Negatif'
print(result)

Positif

In [38]:
#one liner conditional statement more than 1 conditional
num = -2

result = 'Positif' if num > 0 else 'Netral' if num == 0 else 'Negatif'
print(result)

Negatif

#### Conditional statement Berganda

In [39]:
#multi conditional statement
#dalam kumpulan data kependudukan kita ingin membagi menjadi beberapa kategori umur
usia=20

if usia<6:
    kelompok='balita'
elif usia>=6 and usia<=12:
    kelompok='anak-anak'
elif usia>=13 and usia<=22:
    kelompok='remaja'
elif usia>=23 and usia<=60:
    kelompok='dewasa'
else:
    kelompok='lansia'

print(kelompok)

remaja

In [40]:
#multi conditional statement
#dalam kumpulan data kependudukan kita ingin membagi menjadi beberapa kategori umur
usia=20

if usia<6:
    kelompok='balita'
elif usia<=12:
    kelompok='anak-anak'
elif usia<=22:
    kelompok='remaja'
elif usia<=60:
    kelompok='dewasa'
else:
    kelompok='lansia'

print(kelompok)

remaja

#### Mengapa perlu menggunakan elif

In [41]:
usia=5

if usia<6:
    kelompok_usia='balita'
elif usia<=12:
    kelompok_usia='anak-anak'

kelompok_usia

'balita'

In [42]:
usia=5

if usia<6:
    kelompok_usia='balita'
if usia<=12:
    kelompok_usia='anak-anak'

kelompok_usia

'anak-anak'

Dengan menggunakan elif jika sudah memenuhi kondisi maka akan berhenti, sedangkan jika tanpa elif (langsung if) maka value akan ter replace

#### Mini Quiz | Challenge Time #1

1. Buatlah syntax IF untuk melakukan pengecekan apakah plat nomor kendaraan B 1256 AE masuk plat genap atau ganjil !
      
2. Buatlah syntax IF untuk melakukan pengecekan apakah variabel kategori1 ada di dalam list kategori, dimana

kategori1 = 'Fashion Pria' <br>
list_kategori = ['Handphone', 'Sepeda', 'Makanan', 'Fashion Wanita']

In [43]:
#1
plat = 'B 1256 AE'

'GENAP' if int(plat.split(' ')[1])%2 == 0 else 'GANJIL'

'GENAP'

In [10]:
#2
kategori1 = 'Fashion Pria'
list_kategori = ['Handphone', 'Sepeda', 'Makanan', 'Fashion Wanita']

if(kategori1 in list_kategori):
  status = 'Ada'
else:
  status = 'Tidak Ada'
print(status)

Tidak Ada

#### Nested Conditional Statement
if di dalam if

In [ ]:
#Concept Nested Conditional Statements
#contoh if di dalam if
if expression1:
    if expression11:
else:
    statement2(s)

In [11]:
is_java = True
total_order = 101

if is_java == True: #context pembagian java dan non java
    if total_order > 100:
        action = 3
    else:
        action = 1
else: #context pembagian java dan non java
    if total_order > 50:
        action = 3
    else:
        action = 1

print("Action penambahan", action, "point")

Action penambahan 3 point

In [12]:
nilai_x1=100
nilai_x2=50

total_nilai = nilai_x1 + nilai_x2 #syarat1
x1_pass = nilai_x1 > 50 #syarat2 part1
x2_pass = nilai_x2 > 50 #syarat2 part2

if total_nilai>140: # context syarat 1
    syarat1 = 'lolos'
    if x1_pass and x2_pass: # context syarat 2
        syarat2 = 'lolos'
        result = 'lolos'
    else:
        syarat2 = 'tidak lolos'
        result = 'tidak lolos'
else:
    syarat1 = 'tidak lolos'
    if x1_pass and x2_pass:
        syarat2 = 'lolos'
        result = 'tidak lolos'
    else:
        syarat2 = 'tidak lolos'
        result = 'tidak lolos'

print('syarat 1 =', syarat1)
print('syarat 2 =', syarat2)
print('Hasil =', result)

syarat 1 = lolos
syarat 2 = tidak lolos
Hasil = tidak lolos

In [13]:
#kondisi jika langsung kita tidak bisa mengetahui syarat apa yang membuat tidak lolos

nilai_x1=100
nilai_x2=50

#2 condition
if (nilai_x1+nilai_x2>140) and (nilai_x1>50 and nilai_x2>50):
    result = 'lolos'
else:
    result = 'tidak lolos'

print('Hasil = '+result)

Hasil = tidak lolos

In [14]:
# versi tidak menggunakan nested conditional statement

nilai_x1=100
nilai_x2=50

total_nilai = nilai_x1 + nilai_x2
x1_pass = nilai_x1 > 50
x2_pass = nilai_x2 > 50

#pengecekan syarat 1
if total_nilai>140:
    syarat1 = 'lolos'
else:
    syarat1 = 'tidak lolos'

#pengecekan syarat 2
if x1_pass>50 and x2_pass>50:
    syarat2 = 'lolos'
else:
    syarat2 = 'tidak lolos'

#melakukan pengecekan hasil akhir
if syarat1 == 'lolos' and syarat2 =='lolos':
    hasil = 'lolos'
else:
    hasil ='tidak lolos'

print('syarat 1 =', syarat1)
print('syarat 2 =', syarat2)
print('Hasil =', hasil)

syarat 1 = lolos
syarat 2 = tidak lolos
Hasil = tidak lolos

#### Mini Quiz | Challenge Time #2

Untuk menjadi seller premium seorang seller perlu memenuhi syarat-syarat berikut:
- Berhasil menjual 1000 produk
- memiliki feedback positif > 600

Buatlah syntax nested conditional statement (if di dalam if) yang sesuai dengan kasus tersebut.<br> Kemudian uji coba hasil nya dengan case sebagai berikut:<br>
1. sold = 1020
2. pos_feed = 575

In [15]:
#challenge time
sold = 1020
pos_feed = 575

#### Conditional Statement in Dataframe

In [17]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Colab Notebooks/RAKAMIN PERSONAL/learning/data

Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks/RAKAMIN PERSONAL/learning/data

In [18]:
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,.0f}'.format

df_summarize = pd.read_csv('monthly_rakamin_customer_order.csv')
df_summarize.tail()

,order_month,full_name,user_id,phone,city,province,email,total_order,total_gmv,total_visit
332,2022-06-01,Faruq Adi,10000030,628567812319,Makassar,Sulawesi Selatan,faruq@yahoo.com,201,5490000,773
333,2022-06-01,Abrar Adi,10000053,628223411218,Surabaya,Jawa Timur,abrar.adi@yahoo.co.id,110,2987500,276
334,2022-06-01,Johan Imawan,10000054,628223412323,Balikpapan,Kalimantan Timur,johan.imawan@yahoo.com,95,2705000,258
335,2022-06-01,Muhammad Ammar,10000055,628223412111,Surabaya,Jawa Timur,muh.ammar@gmail.com,30,760000,103
336,2022-05-01,Dodo Putro Aji,10000023,628567812312,Surabaya,Jawa Timur,dodo@gmail.com,15,605000,83

In [19]:
#menggunakan fungsi where pada package numpy
df_summarize['group_order'] = np.where(df_summarize['total_order'] > 30, 'High', 'Low')

In [20]:
df_summarize['is_jatim'] = np.where(df_summarize['province'] == 'Jawa Timur', True, False)

In [21]:
# df_summarize['column_name'] = np.where(expression, value True, value False)

In [22]:
df_summarize.head()

,order_month,full_name,user_id,phone,city,province,email,total_order,total_gmv,total_visit,group_order,is_jatim
0,2018-01-01,Ahmad Budiman,10000011,628785222211,Jakarta Pusat,DKI Jakarta,ahmad@gmail.com,125,3490000,230,High,False
1,2018-01-01,Azzam Haqq,10000012,628785222212,Surabaya,Jawa Timur,azzam@gmail.co.id,173,4757500,304,High,True
2,2018-01-01,Amrina Putri,10000013,628785222213,Jakarta Pusat,DKI Jakarta,amrina@yahoo.co.id,20,550000,62,Low,False
3,2018-01-01,Aan Utama,10000014,628785222214,Medan,Sumatra Utara,aan@yahoo.com,18,495000,100,Low,False
4,2018-01-01,Adam Adi,10000015,628785222215,Jakarta Timur,DKI Jakarta,adam@gmail.com,159,4372500,524,High,False

In [23]:
#menggunakan fungsi where pada package numpy multi
df_summarize['group_order_multi'] = np.where(df_summarize['total_order'] > 100, 'High',
                                             np.where(df_summarize['total_order'] > 30, 'Mid', 'Low'))

In [24]:
#menggunakan fungsi where pada package numpy multi
df_summarize['group_order_multi'] = np.where(df_summarize['total_order'] > 100, 'High',
                                             np.where(df_summarize['total_order'] > 30, 'Mid1',
                                             np.where(df_summarize['total_order'] > 10, 'Mid2','Low')))

In [25]:
df_summarize.columns

Index(['order_month', 'full_name', 'user_id', 'phone', 'city', 'province',
       'email', 'total_order', 'total_gmv', 'total_visit', 'group_order',
       'is_jatim', 'group_order_multi'],
      dtype='object')

In [26]:
df_summarize[['order_month', 'full_name', 'user_id', 'phone', 'city', 'province',
       'email', 'total_order', 'total_gmv', 'total_visit','group_order_multi']].head(10)

,order_month,full_name,user_id,phone,city,province,email,total_order,total_gmv,total_visit,group_order_multi
0,2018-01-01,Ahmad Budiman,10000011,628785222211,Jakarta Pusat,DKI Jakarta,ahmad@gmail.com,125,3490000,230,High
1,2018-01-01,Azzam Haqq,10000012,628785222212,Surabaya,Jawa Timur,azzam@gmail.co.id,173,4757500,304,High
2,2018-01-01,Amrina Putri,10000013,628785222213,Jakarta Pusat,DKI Jakarta,amrina@yahoo.co.id,20,550000,62,Mid2
3,2018-01-01,Aan Utama,10000014,628785222214,Medan,Sumatra Utara,aan@yahoo.com,18,495000,100,Mid2
4,2018-01-01,Adam Adi,10000015,628785222215,Jakarta Timur,DKI Jakarta,adam@gmail.com,159,4372500,524,High
5,2018-01-01,Budi Utomo,10000016,628785222216,Bandung,Jawa Barat,budi@gmail.co.id,138,3795000,345,High
6,2018-02-01,Bayu Aji,10000017,628785222217,Semarang,Jawa Tengah,bayu@yahoo.co.id,78,2145000,194,Mid1
7,2018-02-01,Bila Syahputri,10000018,628785222218,Bandung,Jawa Barat,bila@yahoo.com,195,5362500,550,High
8,2018-02-01,Chika Ayu,10000019,628785222219,Semarang,Jawa Tengah,chika@gmail.com,146,4015000,283,High
9,2018-02-01,Cantika Putri Rahayu,10000020,628785222220,Bandung,Jawa Barat,cantika@gmail.co.id,21,577500,64,Mid2

#### Mini Quiz | Challenge Time #3

Menggunakan dataset <b>monthly_rakamin_customer_order</b>, tambahkan kolom <b>is_higher_gmv</b> dengan logik jika

Total GMV lebih besar dari rata-rata GMV bulanan customer maka True namun jika tidak maka False <br>

<b>Hint:</b> <br>
Buat dataframe baru terlebih dulu dengan menggunakan fungsi Group by kemudian di merge / gunakan fungsi .transform()

In [27]:
#challenge time

import pandas as pd
import numpy as np

pd.options.display.float_format = '{:,.0f}'.format #formating float

In [80]:
df = pd.read_csv('monthly_rakamin_customer_order.csv')
df.head()

,order_month,full_name,user_id,phone,city,province,email,total_order,total_gmv,total_visit
0,2018-01-01,Ahmad Budiman,10000011,628785222211,Jakarta Pusat,DKI Jakarta,ahmad@gmail.com,125,3490000,230
1,2018-01-01,Azzam Haqq,10000012,628785222212,Surabaya,Jawa Timur,azzam@gmail.co.id,173,4757500,304
2,2018-01-01,Amrina Putri,10000013,628785222213,Jakarta Pusat,DKI Jakarta,amrina@yahoo.co.id,20,550000,62
3,2018-01-01,Aan Utama,10000014,628785222214,Medan,Sumatra Utara,aan@yahoo.com,18,495000,100
4,2018-01-01,Adam Adi,10000015,628785222215,Jakarta Timur,DKI Jakarta,adam@gmail.com,159,4372500,524

In [90]:
# data = df.groupby(['order_month']).agg({'total_gmv': 'mean'}).reset_index()
# data = data.rename(columns={'total_gmv':'mean_gmv'})

# merged = pd.merge(df, data, on=['order_month'], how='inner')
# merged['is_higher_gmv'] = merged['total_gmv'] > merged['mean_gmv']
# merged
# merged[merged['is_higher_gmv'] == True] #Untuk Mengecek

df_gmv_monthly = df.groupby(['order_month'])['total_gmv'].mean().reset_index()
df_gmv_monthly.columns = ['order_month','avg_total_gmv']
df_gmv_monthly
new = df.merge(df_gmv_monthly, how='inner', on='order_month')
new['is_higher_gmv'] = np.where(new['total_gmv'] > new['avg_total_gmv'], True, False)
# new[new['is_higher_gmv'] == True] #Untuk Mengecek

,order_month,full_name,user_id,phone,city,province,email,total_order,total_gmv,total_visit,avg_total_gmv,is_higher_gmv
0,2018-01-01,Ahmad Budiman,10000011,628785222211,Jakarta Pusat,DKI Jakarta,ahmad@gmail.com,125,3490000,230,"2,910,000",True
1,2018-01-01,Azzam Haqq,10000012,628785222212,Surabaya,Jawa Timur,azzam@gmail.co.id,173,4757500,304,"2,910,000",True
4,2018-01-01,Adam Adi,10000015,628785222215,Jakarta Timur,DKI Jakarta,adam@gmail.com,159,4372500,524,"2,910,000",True
5,2018-01-01,Budi Utomo,10000016,628785222216,Bandung,Jawa Barat,budi@gmail.co.id,138,3795000,345,"2,910,000",True
7,2018-02-01,Bila Syahputri,10000018,628785222218,Bandung,Jawa Barat,bila@yahoo.com,195,5362500,550,"3,121,250",True
...,...,...,...,...,...,...,...,...,...,...,...,...
323,2022-05-01,Dodo Putro Aji,10000023,628567812312,Surabaya,Jawa Timur,dodo@gmail.com,63,1695000,162,"1,668,889",True
326,2022-05-01,Indah Muwarni,10000056,628223412123,Surabaya,Jawa Timur,indah.muwarni@gmail.co.id,125,4102500,488,"1,668,889",True
330,2022-06-01,Eka Rahayu,10000027,628567812316,Palembang,Sumatra Selatan,eka@gmail.com,166,4527500,343,"3,053,889",True
331,2022-06-01,Ela,10000028,628567812317,Makassar,Sulawesi Selatan,ela@gmail.co.id,186,5077500,659,"3,053,889",True
333,2022-06-01,Faruq Adi,10000030,628567812319,Makassar,Sulawesi Selatan,faruq@yahoo.com,201,5490000,773,"3,053,889",True

#### Tetap Semangat Belajar Python. Thank you!