In [1]:
import pandas as pd
import numpy as np

In [2]:
#####  REMARK THIS SECTION IF YOU ARE USING JUPITER NOTEBOOK OR VSCODE ######
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Colab Notebooks/RAKAMIN PERSONAL/learning/Homework Data Processing

Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks/RAKAMIN PERSONAL/learning/Homework Data Processing

In [42]:
data = pd.read_csv('job_data_analyst_details.csv')
data.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Founded,Type of ownership,Industry,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",1961,Nonprofit Organization,Social Assistance,$100 to $500 million (USD),-1,TRUE
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",1893,Nonprofit Organization,Health Care Services & Hospitals,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",2003,Company - Private,Internet,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",2002,Subsidiary or Business Segment,IT Services,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",2009,Company - Private,Sports & Recreation,$100 to $500 million (USD),DraftKings,TRUE

In [11]:
res = data[(data['Location'].str.contains('Houston'))]
res['Rating'].mean()

3.2780821917808223

In [34]:
b = data[(data['Industry'] > 'Industry') & (data['Founded'] > 2015)]
b.groupby('Job Title').agg('count')

,Unnamed: 0,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Founded,Type of ownership,Industry,Revenue,Competitors,Easy Apply
Job Title,,,,,,,,,,,,,
Ad Integrity Data Analyst-ATX,1,1,1,1,1,1,1,1,1,1,1,1,1
Bilingual (Chinese) Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
Billingual Chinese - Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
Business Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
Data Analyst (Finance),1,1,1,1,1,1,1,1,1,1,1,1,1
Data Governance Business Information Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
Data Scientist/Analyst - Wilbur Labs,1,1,1,1,1,1,1,1,1,1,1,1,1
Enterprise Data Office Analyst IV,1,1,1,1,1,1,1,1,1,1,1,1,1
"Financial Data Analyst - Data Mining, Analytics, Reporting",1,1,1,1,1,1,1,1,1,1,1,1,1
Junior Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
Operations Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1
"Principal Data Analyst, LATAM – Disney Streaming Services",1,1,1,1,1,1,1,1,1,1,1,1,1
"Senior Analyst, Data Instrumentation & Quality (Disney+)",1,1,1,1,1,1,1,1,1,1,1,1,1
Senior Data Analyst,3,3,3,3,3,3,3,3,3,3,3,3,3
Senior Data Analyst - User Growth,1,1,1,1,1,1,1,1,1,1,1,1,1
"Sr. Data Analyst - Analytics, Marketing, CPG",1,1,1,1,1,1,1,1,1,1,1,1,1
Sr. Data Analyst — US Safety,1,1,1,1,1,1,1,1,1,1,1,1,1
Survey Data Analyst,1,1,1,1,1,1,1,1,1,1,1,1,1

In [37]:
a = data[data['Founded'] == 2018]
b = data[data['Founded'] == 1995]
c = a.append(b)
c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 36 to 2233
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         53 non-null     int64
 1   Job Title          53 non-null     object
 2   Salary Estimate    53 non-null     object
 3   Job Description    53 non-null     object
 4   Rating             53 non-null     float64
 5   Company Name       53 non-null     object
 6   Location           53 non-null     object
 7   Headquarters       53 non-null     object
 8   Founded            53 non-null     int64
 9   Type of ownership  53 non-null     object
 10  Industry           53 non-null     object
 11  Revenue            53 non-null     object
 12  Competitors        53 non-null     object
 13  Easy Apply         53 non-null     object
dtypes: float64(1), int64(2), object(11)
memory usage: 6.2+ KB

<ipython-input-37-a1c3dc329fde>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  c = a.append(b)

In [43]:
d = data[(data['Founded'] == 2017) & (data['Rating'] >= 3.5) & (data['Rating'] <= 4.5)]
d['new_rating'] = data['Rating']+0.5
d['new_rating'].mean()

<ipython-input-43-b11a2e6bad5a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['new_rating'] = data['Rating']+0.5

4.311111111111111

In [47]:
df1 = data[(data['Job Description'].str.contains('attitude')) & (data['Rating'] >= 1)]
df2 = data[(data['Location'] == 'New York, NY') & (data['Rating'] >= 1)]
df3 = df1.append(df2)
df3['Rating'].mean()

<ipython-input-47-76a0f30813ac>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df3 = df1.append(df2)

3.7101983002832855

In [48]:
asdf = data[(data['Location'].isin(['Lake Success, NY', 'Los Angeles, CA'])) & (data['Job Description'].str.contains('SQL'))]
asdf

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Founded,Type of ownership,Industry,Revenue,Competitors,Easy Apply
234,234,Data Analyst,$41K-$78K (Glassdoor est.),ProHEALTH is one of the largest private multi-...,2.7,ProHEALTH Care\n2.7,"Lake Success, NY","Lake Success, NY",1997,Subsidiary or Business Segment,Health Care Services & Hospitals,Unknown / Non-Applicable,"Northwell Health, Stony Brook University Medic...",-1
238,238,Data Analyst,$41K-$78K (Glassdoor est.),This is an outstanding 2 year contract opportu...,5.0,Professional Resource Group\n5.0,"Lake Success, NY","Spring, TX",-1,Company - Private,Advertising & Marketing,Less than $1 million (USD),-1,-1
247,247,Reporting Analyst Data Analyst,$45K-$88K (Glassdoor est.),Job Description\nTitle: Reporting Analyst / Da...,-1.0,APR Staffing,"Lake Success, NY",-1,-1,-1,-1,-1,-1,-1
281,281,Encounter Data Analyst,$84K-$90K (Glassdoor est.),"Encounter Data Analyst, Lake Success\nGeneral ...",3.5,Integra Managed Care\n3.5,"Lake Success, NY","Lake Success, NY",-1,Subsidiary or Business Segment,Health Care Services & Hospitals,Unknown / Non-Applicable,-1,-1
366,366,QA Data Analyst,$77K-$132K (Glassdoor est.),This is an outstanding 2 year contract opportu...,5.0,Professional Resource Group\n5.0,"Lake Success, NY","Spring, TX",-1,Company - Private,Advertising & Marketing,Less than $1 million (USD),-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,660,Sr Performance Metrics Data Analyst,$65K-$81K (Glassdoor est.),Position InformationJob Title: Sr. Performance...,-1.0,BBCN Bank,"Los Angeles, CA",-1,-1,-1,-1,-1,-1,-1
675,675,Sr Performance Metrics Data Analyst,$65K-$81K (Glassdoor est.),Position Information\n\nJob Title: Sr. Perform...,2.6,Bank Of Hope\n2.6,"Los Angeles, CA","Los Angeles, CA",-1,Company - Public,-1,$100 to $500 million (USD),-1,-1
676,676,Student Data Compliance Analyst,$65K-$81K (Glassdoor est.),About Us\n\nKIPP SoCal Public Schools (KIPP So...,3.3,KIPP SoCal Public Schools\n3.3,"Los Angeles, CA","Los Angeles, CA",2003,Nonprofit Organization,K-12 Education,$50 to $100 million (USD),-1,-1
707,707,Systems and Data Analyst,$113K-$132K (Glassdoor est.),Job Description\nAdvance knowledge in the foll...,2.4,To Help Everyone Health & Wellness Centers\n2.4,"Los Angeles, CA","Los Angeles, CA",-1,Nonprofit Organization,-1,Unknown / Non-Applicable,-1,-1
714,714,Sr. Data Analyst — US Safety,$113K-$132K (Glassdoor est.),Sr. Data Analyst — US Safety\nLos AngelesOpera...,3.8,TikTok\n3.8,"Los Angeles, CA","Los Angeles, CA",2016,Company - Private,Internet,Unknown / Non-Applicable,-1,-1

In [49]:
asdf.to_excel('analysis_result.csv')

ValueError: No engine for filetype: 'csv'